/// Flutter icons InstagramIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  InstagramIcons
///      fonts:
///       - asset: fonts/InstagramIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class InstagramIcons {
  InstagramIcons._();

  static const _kFontFam = 'InstagramIcons';

  static const IconData comment_outlined = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData heart_outlined = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData home_outlined = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData inbox_outlined = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData new_outlined = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData photo_outline = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData search_outlined = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData send_outlined = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData user_outlined = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe80c, fontFamily: _kFontFam);
}
